win:
	@echo Compiling code...
	@gcc -o app.exe *.c 
	@echo Compile done. Launching app...
	@./app.exe
linux:
	@echo Compiling code...
	@gcc -o app.out *.c 
	@echo Compile done. Launching app...
	@./app.out

